# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://vegetaz.github.io/
title: Van Van Nguyen
email: your-email@domain.com
author: Nguyễn Văn Vận
description: > # "Write an awesome description for your new site here. 
  A hard-working person who is always responsible for assigned works and try to finish them with the best quality.
  A good single-player as well as a team-player. 
copyright: 'Copyright &copy; 2015 Nguyễn Văn Vận. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/vanfsn
  - title: github
    url: https://github.com/vegetaz
  - title: linkedin
    url: https://www.linkedin.com/in/vanz25
